export const TOGGLE_SEARCH_OVERFLOW = 'TOGGLE_SEARCH_OVERFLOW';
export const OVERFLOW_HIDDEN_STATUS = 'OVERFLOW_HIDDEN_STATUS';
export const SHOW_DIALOG_STATUS = 'SHOW_DIALOG_STATUS';

// discovery
export const SET_ORDER_PARAMS = 'SET_ORDER_PARAMS';
export const SET_CHOOSE_ACTIVITY = 'SET_CHOOSE_ACTIVITY';
